# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Enterprise Subscription(1ccb1bf8-f93f-42dc-886b-acdbc6f972eb)'
    subscriptionId: '1ccb1bf8-f93f-42dc-886b-acdbc6f972eb'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'storagetest1'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName mytest001 -linkedTemplateUri https://raw.githubusercontent.com/suncityxmu/azuretest/master/CreateWebApp/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
