name: manage-azure-policy-64a79d97
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Function_apps_should_use_managed_identity_0da106f2-4ca3-48e8-bc85-c638fe6aea8f/**'
#      - .github/workflows/manage-azure-policy-64a79d97.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_64a79d97}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Function_apps_should_use_managed_identity_0da106f2-4ca3-48e8-bc85-c638fe6aea8f/**
